services:
  capstone_postgres:
    image: postgres
    ports:
      - "${POSTGRES_HOST}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - event_volume:/var/lib/postgres/data

volumes:
  event_volume: